promptToReturnFromSubprocess: false

gui:
  theme:
    activeBorderColor:
      - '#585858'
      - bold
    inactiveBorderColor:
      - '#464646'
    searchingActiveBorderColor:
      - '#8787af'
    optionsTextColor:
      - '#1e66f5'
    selectedLineBgColor:
      - '#585858'
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - '#179299'
    cherryPickedCommitBgColor:
      - '#8fafd7'
    markedBaseCommitFgColor:
      - '#5f8787'
      # markedBaseCommitBgColor:
      #   - yellow
    unstagedChangesColor:
      - '#5f8787'
    defaultFgColor:
      - '#bcbcbc'

  authorColors:
    '*': '#5f8787'
