(("default"   . ((user-emacs-directory . "~/dev/my-stuff/.emacs.d")))
 ("bankrupcy" . ((user-emacs-directory . "~/dev/my-stuff/emacs-new/.emacs.d")))
 ("doom"      . ((user-emacs-directory . "~/dev/tools/doom-emacs")
                 (env . (("DOOMDIR" . "~/.doom.d")))))
 )
