#!/usr/bin/env bash

if [[ "$TERM" == "dumb" ]]; then
    COLOR_RED=''
    COLOR_NONE=''
else
    COLOR_RED='\033[0;31m'
    COLOR_NONE='\033[0m'
fi

command -v git-lfs >/dev/null 2>&1
hasGitLFS=$?

if [ ${hasGitLFS} -ne 0 ]; then
    printf "${COLOR_RED}WARNING: This repository is configured for Git LFS but 'git-lfs' was not found on your path.${COLOR_NONE}\n"
    exit 2
else
    git lfs post-merge "$@"
fi
