#!/bin/bash

if [[ "$TERM" == "dumb" ]]; then
    COLOR_RED=''
    COLOR_NONE=''
else
    COLOR_RED='\033[0;31m'
    COLOR_NONE='\033[0m'
fi

branchName=$(git rev-parse --abbrev-ref HEAD)

if [[ "${branchName}" == "master" ]]; then
    printf "${COLOR_RED}WARNING: Checking out master is deprecated${COLOR_NONE}\n"
fi
