check_for_update_on_startup = false

notify = ["/Users/white1/dev/my-stuff/dotfiles/codex/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/white1/dev/my-stuff/github-repos"]
trust_level = "trusted"

[projects."/Users/white1/dev/scratchpad/testing"]
trust_level = "trusted"

[tui.model_availability_nux]
"gpt-5.5" = 1

[features]
memories = true
runtime_metrics = true
multi_agent_v2 = true
js_repl = false

[marketplaces.openai-bundled]
last_updated = "2026-06-16T11:19:31Z"
source_type = "local"
source = "/Users/white1/dev/my-stuff/dotfiles/codex/.codex/.tmp/bundled-marketplaces/openai-bundled"

[desktop]
ambient-suggestions-enabled = false
conversationDetailMode = "STEPS_COMMANDS"

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/white1/.codex"
CODEX_HOME = "/Users/white1/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "89809670b247cbaffbc4f87d9fa9742a9038c0f4a06fb822d7f85ff19bf24215"
BROWSER_USE_AVAILABLE_BACKENDS = "iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.609.71450"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[plugins."browser@openai-bundled"]
enabled = true
