################################################################################
# Prerequisites
################################################################################

tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

cask "adoptopenjdk8"

################################################################################
# Applications
################################################################################

cask "anki"
cask "beyond-compare"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "keybase"
cask "licecap"

################################################################################
# Utilities
################################################################################

brew "cmake"
brew "coreutils"
brew "entr"
brew "findutils"
brew "gnu-sed"
brew "graphviz"
brew "htop"
brew "jq"
brew "ncdu"
brew "neovim"
brew "openssh"
brew "pkg-config"
brew "sampler"
brew "slackcat"
brew "the_silver_searcher"
brew "tig"
brew "tree"
brew "watch"
brew "wget"
brew "zsh"
cask "scroll-reverser"

# Document and image manipulation
brew "imagemagick"
brew "pandoc"

# tmux
brew "tmux"
brew "tmuxinator"
brew 'reattach-to-user-namespace'

################################################################################
# Development
################################################################################

# Version control
brew "git"
brew "git-secret"
brew "gnupg"

# Java
cask "visualvm"
brew "maven"
brew "gradle"

# Clojure
brew "leiningen"

# Scala
brew "mill"
brew "sbt"
brew "scala"
brew "ammonite-repl"

# Haskell
brew "cabal-install"
brew "haskell-stack"

# Python
brew "python"
brew "python@2"

# Elm
brew "elm"

# Ruby
brew "ruby"

# Node
brew "node"

# AWS
brew "awscli"
brew "terraform", link: false
brew "tfenv", link: true

# SQL
cask "sequel-pro"
cask "sqlworkbenchj"

# Shell
brew "bats-core"

# Linters
brew "aspell"
brew "shellcheck"
brew "yamllint"

################################################################################
# Fun
################################################################################

brew "cataclysm"
brew "nethack"
